plugin: hive_inventory
name: procube-products
stages:
  production:
    provider: aws
    separate_repository: False
    number_of_hosts: 3
    cidr: 192.168.0.0/24
    region: ap-northeast-1
    disk_size: 50
    mirrored_disk_size: 20
    instance_type: t3.large
    repository_instance_type: t3.large
    repository_disk_size: 50
    subnets:
    - cidr: 192.168.0.0/26
      name: subnet-a
      available_zone: ap-northeast-1b
    - cidr: 192.168.0.64/26
      name: subnet-b
      available_zone: ap-northeast-1d
    - cidr: 192.168.0.128/26
      name: subnet-c
      available_zone: ap-northeast-1c

