---
plugin: hive_services
services:
  # MongoDB Database
  idm3-mongodb:
    image: mongo:7.0
    # ports:
    # - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: idm3
    volumes:
    - source: mongodb_data
      target: /data/db
      type: volume
      drbd:
        fstype: xfs
        size: 5G
    - source: mongodb_config
      target: /data/configdb
      type: volume
      drbd:
        fstype: xfs
        size: 1G

  # BindBroker Service
  idm3-bindbroker:
    image: docker-repository.procube.jp/idm-bindbroker:latest
    # ports:
    # - "8090:8090"
    # - "8091:8091"
    # - "8092:8092"
    # - "8093:8093"
    # - "8094:8094"
    environment:
      NODE_ENV: development
      IDM_DB_MONGO_HOST: idm3-mongodb
      IDM_DB_MONGO_OPTION: '{"auth":{"username":"root","password":"password"},"authSource":"admin"}'
      IDM_PROVISIONING_TOMCAT_HOST: idm3-tomcat

  # Tomcat Service
  idm3-tomcat:
    image: docker-repository.procube.jp/idm-tomcat:latest
    # ports:
    # - "8080:8080"
    environment:
      BINDBROKER_URL: http://idm3-bindbroker:8090
      JAVA_OPTS: -Xmx1024m -Xms512m

  # Gateway Service (Apache HTTP Server)
  idm3-gateway:
    image: docker-repository.procube.jp/idm-gateway:0.0.7-rc.2
    ports:
    - "10443:9443"
    initialize_roles:
      - idm-download
      # - idm-init
    environment:
      # 認証設定
      AUTH_METHOD: saml
      AUTH_REALM: NetSoarer ID Manager V3
      # SAML設定
      SAML_UID_ATTR: uid
      SAML_GROUP_ATTR: HTTP_REMOTEGROUP
      SAML_LOGOUT_URL: https://auth.{{ domain }}/Shibboleth.sso/Logout
      # バックエンドURL設定
      WEB_BACKEND_URL: http://idm3-web:3000
      # MongoDB設定（idm3ctlコマンド用）
      MONGO_HOST: idm3-mongodb
      MONGO_PORT: "27017"
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_AUTH_DB: admin
      # BindBroker設定（idm3ctlコマンド用）
      BINDBROKER_HOST: idm3-bindbroker
      BINDBROKER_MANAGEMENT_PORT: "8094"
      BINDBROKER_HMR_RESTART_ENABLED: "true"
    labels:
      published_name: idm3
      webgate:
        proxies:
        - target_port: 80
          readTimeout: 7200
          maxBodySize: 10
          pathPattern: /
          authentication: saml
        - target_port: 80
          postfix: ":chpw"
          pathPattern: /changePassword

  # Web Frontend Service
  idm3-web:
    image: docker-repository.procube.jp/idm-web:latest
    environment:
      # NEXT_PUBLIC_TRUSTED_ORIGIN: https://localhost:9443
      NEXT_PUBLIC_TRUSTED_ORIGIN: https://super-duper-space-halibut-6j564xr5559hrg6p-10443.app.github.dev
      NEXT_API_URL: http://idm3-bindbroker:8090/IDManager
      NEXT_CSV_URL: http://idm3-bindbroker:8091/IDManagerCSV
      NEXT_PDF_URL: http://idm3-tomcat:8080/PdfReport
      NEXT_CHANGEPASSWORD_URL: http://idm3-tomcat:8080/changePassword
      NEXT_ADPASSWORDSYNC_URL: http://idm3-tomcat:8080/ADPasswordSync
      NEXT_MAILCONFIRM_URL: http://idm3-tomcat:8080/MailConfirm
  ldap:
    image:
      from: procube/openldap:latest
      roles:
      - python-aptk
      - ldap
    initialize_roles:
      - ldap-init
    environment:
      LDAP_CONFIG_PASSWORD: "{{ credentials.ldap_config_password }}"
      LDAP_NOFILE: "1024"
    volumes:
    - source: ldap_data
      target: /var/lib/openldap/openldap-data
      type: volume
      drbd:
        fstype: xfs
        size: 500M
    - source: ldap_config
      target: /etc/openldap/slapd.d
      type: volume
      drbd:
        fstype: xfs
        size: 500M
  # ID Manager V2 Service (Legacy)
  # idm:
  #   image:
  #     from: procube/alma8-standalone-base
  #     roles:
  #       - hive-trust-ca
  #       - timezone
  #       - netsoarer-products
  #       - idm
  #       - hive-syslog
  #       - prov-tools
  #   standalone: True
  #   ports:
  #   - "10443:9443"
  #   - "18090:8090"
  #   labels:
  #     published_name: idm
  #     webgate:
  #       proxies:
  #       - target_port: 80
  #         readTimeout: 7200
  #         maxBodySize: 10
  #         pathPattern: /
  #         authentication: saml
  #       - target_port: 80
  #         postfix: ":chpw"
  #         pathPattern: /changePassword
  #   initialize_roles:
  #     #- idm-download
  #     - idm-init
  #   volumes:
  #   - source: idm_mysql
  #     target: /var/lib/mysql
  #     type: volume
  #     drbd:
  #       fstype: xfs
  #       size: 300M
  #   - source: idm_mongo
  #     target: /var/lib/mongo
  #     type: volume
  #     drbd:
  #       fstype: xfs
  #       size: 10G
  #   - source: idm_eu_app_csv
  #     target: /var/lib/eu_app
  #     type: volume
  #     drbd:
  #       fstype: xfs
  #       size: 5G
  #   backup_scripts:
  #   - name: idm
  #     container: idm
  #     backup_command: . /etc/profile.d/java.sh; idm2ctl backup -f /root/today.tar.gz
  #     restore_command: . /etc/profile.d/java.sh;idm2ctl restore -f /root/today.tar.gz
  #     backup_file: /root/today.tar.gz
  #     restore_file: /root/today.tar.gz
  #     cleanup_days_before: 3
  #   - name: idm_eu_app_csv
  #     container: idm
  #     directory: /var/lib/eu_app
  #     cleanup_days_before: 3
