---
plugin: hive_services
services:
  webgate:
    image:
      from: almalinux/9-init
      roles:
      - timezone
      - netsoarer-products
      - hive-syslog
      - webgate
    standalone: True
    ports:
    - "8080"
    - "443:443"
    - "80:80"
    initialize_roles:
    - webgate-init
    - webgate-certbot
    volumes:
    - source: webgate_consul
      target: /var/consul
      type: volume
      drbd:
        fstype: xfs
        size: 500M
    - source: webgate_certbot
      target: /etc/letsencrypt
      type: volume
      drbd:
        fstype: xfs
        size: 1G